project:
  type: website
  output-dir: docs

website:
  title: "MAD-II"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/w1.qmd
        text: Week 1
      - href: pages/w2.qmd
        text: Week 2
      - href: pages/w3.qmd
        text: Week 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true